### ISSUE TITLE
建议降低耦合度

### ISSUE THREAD

**Issue by fg2q1q3q** [zaaach/CityPicker#1]
建议将该控件封装为ViewGroup或Fragment，内部处理定位、搜索、拼音排序、数据库读取以及拼音条拖动定位等逻辑，外部暴漏方法供用户设置热门城市、监听item点击事件（热门/全部/搜索/定位）等

**Comment by zaaach** [comment]
恩，有时间再完善吧

**Comment by Lsy1992** [comment]
请问如何将服务器获取到的城市列表添字母索引啊？

**Comment by zohar-soul** [comment]
我已经提了pr  改为了Fragment
合并一下好了

**Comment by syBlack** [comment]
您好，请问下我按照这个代码在eclipse上写了一遍之后无法打开data下的数据库，我看了下目录里面没有database这个目录，但是mkdirs这个方法执行了
