### ISSUE TITLE
存在内存泄漏，望大神修复下

### ISSUE THREAD

**Issue by yikeng** [zaaach/CityPicker#10]
D/LeakCanary: * com.zaaach.citypicker.CityPickerActivity has leaked:
03-27 16:02:24.960 12371-12719/? D/LeakCanary: * GC ROOT com.loc.d$b.<Java Local>
03-27 16:02:24.960 12371-12719/? D/LeakCanary: * references com.loc.d$b.a
03-27 16:02:24.960 12371-12719/? D/LeakCanary: * references com.loc.d.d
03-27 16:02:24.960 12371-12719/? D/LeakCanary: * references java.util.ArrayList.array
03-27 16:02:24.960 12371-12719/? D/LeakCanary: * references array java.lang.Object[].[0]
03-27 16:02:24.960 12371-12719/? D/LeakCanary: * references com.zaaach.citypicker.CityPickerActivity$1.this$0 (anonymous implementation of com.amap.api.location.AMapLocationListener)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: * leaks com.zaaach.citypicker.CityPickerActivity instance
03-27 16:02:24.960 12371-12719/? D/LeakCanary: * Retaining: 124 KB.
03-27 16:02:24.960 12371-12719/? D/LeakCanary: * Reference Key: 3ff196aa-dbe0-451c-8291-2f0576e76d02
03-27 16:02:24.960 12371-12719/? D/LeakCanary: * Device: unknown WELINKIO LINK6 link6
03-27 16:02:24.960 12371-12719/? D/LeakCanary: * Android Version: 4.4.2 API: 19 LeakCanary: 1.5 00f37f5
03-27 16:02:24.960 12371-12719/? D/LeakCanary: * Durations: watch=35361ms, gc=147ms, heap dump=881ms, analysis=34278ms
03-27 16:02:24.960 12371-12719/? D/LeakCanary: * Details:
03-27 16:02:24.960 12371-12719/? D/LeakCanary: * Instance of com.loc.d$b
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   a = com.loc.d@1108127720 (0x420cafe8)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   mLooper = android.os.Looper@1109355296 (0x421f6b20)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   mPriority = 0
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   mTid = 12590
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   contextClassLoader = dalvik.system.PathClassLoader@1107626464 (0x420509e0)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   vmThread = java.lang.VMThread@1109351712 (0x421f5d20)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   group = java.lang.ThreadGroup@1101673824 (0x41aa3560)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   uncaughtHandler = null
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   target = null
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   inheritableValues = null
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   interruptActions = java.util.ArrayList@1109340104 (0x421f2fc8)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   localValues = java.lang.ThreadLocal$Values@1108871288 (0x42180878)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   name = java.lang.String@1108842200 (0x421796d8)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   parkBlocker = null
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   id = 398
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   stackSize = 0
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   priority = 5
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   parkState = 1
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   hasBeenStarted = true
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   daemon = false
03-27 16:02:24.960 12371-12719/? D/LeakCanary: * Instance of com.loc.d$b
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   a = com.loc.d@1108127720 (0x420cafe8)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   mLooper = android.os.Looper@1109355296 (0x421f6b20)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   mPriority = 0
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   mTid = 12590
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   contextClassLoader = dalvik.system.PathClassLoader@1107626464 (0x420509e0)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   vmThread = java.lang.VMThread@1109351712 (0x421f5d20)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   group = java.lang.ThreadGroup@1101673824 (0x41aa3560)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   uncaughtHandler = null
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   target = null
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   inheritableValues = null
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   interruptActions = java.util.ArrayList@1109340104 (0x421f2fc8)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   localValues = java.lang.ThreadLocal$Values@1108871288 (0x42180878)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   name = java.lang.String@1108842200 (0x421796d8)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   parkBlocker = null
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   id = 398
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   stackSize = 0
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   priority = 5
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   parkState = 1
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   hasBeenStarted = true
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   daemon = false
03-27 16:02:24.960 12371-12719/? D/LeakCanary: * Instance of com.loc.d
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   w = com.loc.bz@1108802792 (0x4216fce8)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   B = com.amap.api.location.AMapLocationClientOption$AMapLocationMode@1108841440 (0x421793e0)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   C = java.lang.Object@1109248400 (0x421dc990)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   D = com.loc.cu@1108802960 (0x4216fd90)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   E = null
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   v = com.loc.d$b@1108871152 (0x421807f0)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   G = java.lang.String@1108870776 (0x42180678)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   p = null
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   I = com.loc.d$a@1109245464 (0x421dbe18)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   J = com.amap.api.location.AMapLocation@1109327832 (0x421effd8)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   K = null
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   L = java.util.Hashtable@1108127952 (0x420cb0d0)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   l = null
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   k = android.os.Messenger@1109528848 (0x42221110)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   O = io.welink.weather.WeatherApp@1107677968 (0x4205d310)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   j = null
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   i = com.loc.h@1109245648 (0x421dbed0)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   R = org.json.JSONArray@1109500048 (0x4221a090)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   e = null
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   d = java.util.ArrayList@1109335928 (0x421f1f78)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   U = com.loc.d$1@1109281640 (0x421e4b68)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   V = java.util.LinkedList@1109336216 (0x421f2098)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   W = java.util.LinkedList@1109337944 (0x421f2758)
03-27 16:02:24.960 12371-12719/? D/LeakCanary: |   c = com.loc.g@1108802648 (0x4216fc58)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   Y = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   a = com.amap.api.location.AMapLocationClientOption@1109101128 (0x421b8a48)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   b = com.loc.d$d@1108127992 (0x420cb0f8)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   X = 0
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   z = 0.0
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   r = 0
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   q = 0
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   o = 0
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   h = true
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   Q = false
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   P = false
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   N = false
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   M = 0
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   m = 0
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   n = false
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   g = false
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   H = false
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   f = false
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   S = 0
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   s = false
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   t = 240
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   u = 80
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   F = false
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   A = false
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   x = false
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   y = 0.0
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   T = true
03-27 16:02:24.970 12371-12719/? D/LeakCanary: * Instance of java.util.ArrayList
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   static $staticOverhead = byte[48]@1101628801 (0x41a98581)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   static serialVersionUID = 8683452581122892189
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   static MIN_CAPACITY_INCREMENT = 12
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   array = java.lang.Object[12]@1108811528 (0x42171f08)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   size = 1
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   modCount = 1
03-27 16:02:24.970 12371-12719/? D/LeakCanary: * Array of java.lang.Object[]
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   [0] = com.zaaach.citypicker.CityPickerActivity$1@1108894120 (0x421861a8)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   [1] = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   [2] = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   [3] = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   [4] = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   [5] = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   [6] = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   [7] = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   [8] = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   [9] = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   [10] = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   [11] = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: * Instance of com.zaaach.citypicker.CityPickerActivity$1
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   static $staticOverhead = byte[48]@1108080393 (0x420bf709)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   static $change = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   static serialVersionUID = 0
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   this$0 = com.zaaach.citypicker.CityPickerActivity@1107590832 (0x42047eb0)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: * Instance of com.zaaach.citypicker.CityPickerActivity
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   static $staticOverhead = byte[72]@1107773649 (0x420748d1)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   static KEY_PICKED_CITY = java.lang.String@1108126984 (0x420cad08)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   static $change = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   static serialVersionUID = 0
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   clearBtn = android.widget.ImageView@1108906656 (0x421892a0)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   dbManager = com.zaaach.citypicker.db.DBManager@1107652576 (0x42056fe0)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   emptyView = android.widget.LinearLayout@1109373616 (0x421fb2b0)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mAllCities = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mCityAdapter = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mLetterBar = com.zaaach.citypicker.view.SideLetterBar@1108843824 (0x42179d30)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mListView = android.widget.ListView@1109282960 (0x421e5090)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mLocationClient = com.amap.api.location.AMapLocationClient@1109208864 (0x421d2f20)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mResultAdapter = com.zaaach.citypicker.adapter.ResultListAdapter@1109202240 (0x421d1540)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mResultListView = android.widget.ListView@1108795976 (0x4216e248)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   searchBox = android.widget.EditText@1109530744 (0x42221878)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mActionBar = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mActivityInfo = android.content.pm.ActivityInfo@1108885760 (0x42184100)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mAllLoaderManagers = android.util.ArrayMap@1109101304 (0x421b8af8)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mApplication = io.welink.weather.WeatherApp@1107677968 (0x4205d310)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mWindowManager = android.view.WindowManagerImpl@1108141816 (0x420ce6f8)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mWindow = com.android.internal.policy.impl.PhoneWindow@1107664408 (0x42059e18)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mUiThread = java.lang.Thread@1101679976 (0x41aa4d68)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mTranslucentCallback = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mComponent = android.content.ComponentName@1108234312 (0x420e5048)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mToken = android.os.BinderProxy@1108228984 (0x420e3b78)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mContainer = android.app.Activity$1@1107956832 (0x420a1460)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mCurrentConfig = android.content.res.Configuration@1108545704 (0x421310a8)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mDecor = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mTitle = java.lang.String@1108144560 (0x420cf1b0)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mDefaultKeySsb = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mSearchManager = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mResultData = android.content.Intent@1107867912 (0x4208b908)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mEmbeddedID = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mParent = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mMenuInflater = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mFragments = android.app.FragmentManagerImpl@1108801168 (0x4216f690)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mHandler = android.os.Handler@1108193056 (0x420daf20)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mHelper = android.app.swipeback.SwipeBackActivityHelper@1108132152 (0x420cc138)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mManagedDialogs = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mInstanceTracker = android.os.StrictMode$InstanceTracker@1107949368 (0x4209f738)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mInstrumentation = android.app.Instrumentation@1107626272 (0x42050920)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mIntent = android.content.Intent@1108946304 (0x42192d80)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mLastNonConfigurationInstances = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mLoaderManager = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mManagedCursors = java.util.ArrayList@1108200272 (0x420dcb50)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mMainThread = android.app.ActivityThread@1107608376 (0x4204c338)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mLoadersStarted = false
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mIdent = 1114526528
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mFinished = true
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mEnableDefaultActionBarUp = false
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mResultCode = -1
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mDoReportFullyDrawn = false
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mResumed = false
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mDestroyed = true
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mStartedActivity = false
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mStopped = true
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mTemporaryPause = false
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mDefaultKeyMode = 0
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mTitleColor = 0
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mTitleReady = true
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mConfigChangeFlags = 0
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mCheckedForLoaderManager = true
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mChangingConfigurations = false
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mVisibleFromClient = true
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mVisibleFromServer = true
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mChangeCanvasToTranslucent = false
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mWindowAdded = true
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mCalled = true
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mBase = android.app.ContextImpl@1109233888 (0x421d90e0)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mInflater = com.android.internal.policy.impl.PhoneLayoutInflater@1108817048 (0x42173498)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mOverrideConfiguration = null
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mResources = android.content.res.Resources@1107622992 (0x4204fc50)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mTheme = android.content.res.Resources$Theme@1108136680 (0x420cd2e8)
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mThemeResource = 2131296464
03-27 16:02:24.970 12371-12719/? D/LeakCanary: |   mBase = android.app.ContextImpl@1109233888 (0x421d90e0)

**Comment by yikeng** [comment]
在onDestory()里调用
mLocationClient.unRegisterLocationListener(aMapLocationListener);

**Comment by zaaach** [comment]
你这个写在那个Activity里的呢？项目的[CityPickerActivity](https://github.com/zaaach/CityPicker/blob/master/citypicker/src/main/java/com/zaaach/citypicker/CityPickerActivity.java)里在onDestroy()中已经调用mLocationClient.stopLocation();了的

**Comment by yikeng** [comment]
mLocationClient.stopLocation() : 定位服务并不会被销毁，还是持有MapLocationListener对象。使用LeakCanary可以监测到。

**Comment by zaaach** [comment]
试试最新2.0版本
