### ISSUE TITLE
定位失败

### ISSUE THREAD

**Issue by yangruixiang** [zaaach/CityPicker#12]
你好，按钮你上面的步骤试了后，4.4和7.1都不行,请问什么原因

**Comment by zaaach** [comment]
首先是APP签名打包之后才能正常定位的，4.4的应该正常，7.0的可能因为动态权限的问题没有做适配~

**Comment by yangruixiang** [comment]
但是我在设置里面打开权限也是定位失败，4.4的也是，也是重新打的包。

**Comment by zaaach** [comment]
有报什么错误吗

**Comment by zaaach** [comment]
@yangruixiang 用最新的2.0版本试试，去掉了定位功能
