### ISSUE TITLE
Android6.0定位失败

### ISSUE THREAD

**Issue by JiangShuLiang** [zaaach/CityPicker#13]
是不是这个库里没有申请运行时权限？
还望大神能加入一下运行时权限的，晚辈感激不尽！

**Comment by zaaach** [comment]
恩，近期抽时间再完善一下

**Comment by JiangShuLiang** [comment]
非常的感谢！！！！！！还以为你要掉线了233，感谢重新上线！

**Comment by lmdiloveu** [comment]
果然是6.0运行时权限的问题，定位需要运行时处理，不知道啥时候能完善

**Comment by lmdiloveu** [comment]
暂时我的解决方案是，把目标版本调到低于6.0版本也就是23以下，测试成功，能够定位

**Comment by zh476460340** [comment]
使用百度sdk定位必须同时申请定位权限和手机状态权限，否则无法定位
