### ISSUE TITLE
和高德地图冲突怎么办呢

### ISSUE THREAD

**Issue by zhangxiaobin123456** [zaaach/CityPicker#19]
高德地图中引入了定位和地图包，在依赖了选择城市后编译不过，大神指导下

**Comment by kongchengyijian** [comment]
把他的model引入项目，把自己的location删除

**Comment by qiwei0727** [comment]
https://github.com/qiwei0727/CityPicker这里解决了你这个问题

**Comment by zaaach** [comment]
@zhangxiaobin123456 @YinJazz 使用最新的2.0版本
