### ISSUE TITLE
请问如何将城市列表添字母索引啊？

### ISSUE THREAD

**Issue by Lsy1992** [zaaach/CityPicker#2]

**Comment by Lsy1992** [comment]
`   for (int index = 0; index < size; index++){
            //当前城市拼音首字母
            String currentLetter = PinyinUtils.getFirstLetter(mCities.get(index).getPinyin());
            //上个首字母，如果不存在设为""
            String previousLetter = index >= 1 ? PinyinUtils.getFirstLetter(mCities.get(index - 1).getPinyin()) : "";
            if (!TextUtils.equals(currentLetter, previousLetter)){
                letterIndexes.put(currentLetter, index);
                sections[index] = currentLetter;
            }
        }`
只看到在CityListAdapter有这么一段代码来获取对应拼音的？
那么汉字转拼音的操作在哪里设置啊？

**Comment by zaaach** [comment]
项目用的城市是从数据中读取的，数据库中保存的就有拼音的，你可以看下china_cities.db这个文件

**Comment by Lsy1992** [comment]
您这边是直接把拼音数据写死到数据库了？ 
我这如果是外部的一串动态数组数据怎么转换成拼音索引啊。
不太明白，还望赐教

**Comment by zaaach** [comment]
你参考下这个吧https://github.com/promeG/TinyPinyin

**Comment by Lsy1992** [comment]
终于回复我了，~~~~(>_<)~~~~  我这边已经实现好了汉字转拼音了。
遇到的唯一痛苦的问题就是转换好的拼音并没有在列表中进行对应的一个排序，也没有索引标签出现，这个不懂在哪里可以设置，也没看到注释··请谅解我的无知

**Comment by zaaach** [comment]
确定拼音转换正常，City类也正确，还有是否刷新adapter

**Comment by Lsy1992** [comment]
好的谢谢！我再仔细研究一下。
