### ISSUE TITLE
直接添加them报错 

### ISSUE THREAD

**Issue by liupeng110** [zaaach/CityPicker#36]
s\res\merged\debug\values-v24\values-v24.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

**Comment by liupeng110** [comment]
能不能搞个选择之后 直接通过activityresult返回结果的 
或者eventbus发送结果也行啊      用的时候只关注结果不关注页面

**Comment by zaaach** [comment]
@liupeng110 添加的主题需要继承DefaultCityPIckerTheme

**Comment by sunshinecf** [comment]
我都不知道在哪里和你对话 我的qq邮箱不能回复你  先前的帖子不知道去哪里了

**Comment by sunshinecf** [comment]
我能看到你的回复消息，也是邮箱发来的

**Comment by sunshinecf** [comment]
那个style有写  我看到了  我也加到我新创建的activity里面去了   现在就要用  看你人气这么高  来用哈 以前没写过这个

**Comment by liupeng110** [comment]
怎么邮箱也通知我了
