### ISSUE TITLE
定位失败

### ISSUE THREAD

**Issue by wufannet** [zaaach/CityPicker#4]
定位失败,是需要配置自己的高德地图key吗?

**Comment by zaaach** [comment]
是的，需要自己去申请key

**Comment by wufannet** [comment]
谢谢了.建议key代码处直接注释需要 填写自己的key. 谢谢回答.

**Comment by JiangShuLiang** [comment]
我在manifest里填上自己的key，还是照样定位失败。

**Comment by JiangShuLiang** [comment]
关于定位失败：
1，尝试了在manifest里替换掉成自己的AppKey，无果，照样定位失败；
2，尝试了genymotion模拟器和真机运行，无果，照样定位失败；
3，尝试了把高德的错误信息log出来，显示错误码是2，错误信息是wifi信号不足。对照官网的错误表提供的解决方法是：重新尝试。无果，照样定位失败；
P.S：
（1）错误信息：location Error, ErrCode:2, errInfo:WIFI信息不足
（2）官网错误表地址：http://lbs.amap.com/api/android-location-sdk/guide/utilities/errorcode/#v2

最后想问作者，关于定位功能，还要哪儿是需要改动的吗？麻烦告知一下，先感谢了！
PS：看着很多个选择城市的demo，还是你这个做的最好集成。也做的很不错。感谢x3

**Comment by zaaach** [comment]
直接debug运行是定位失败的，需要打包签名apk才能定位成功，还有注意混淆的配置
