### ISSUE TITLE
在fragment里面调用会LayoutInflater.inflate失败，一加载布局就报错

### ISSUE THREAD

**Issue by yangzai100** [zaaach/CityPicker#41]
at com.zaaach.citypicker.CityPickerDialogFragment.onCreateView(CityPickerDialogFragment.java:143)

**Comment by luffykou** [comment]
未设置特定Theme的问题，同#29

注意README中的基本使用：
Step1:
在manifest.xml中给使用CityPicker 的activity添加主题android:theme="@style/DefaultCityPickerTheme"
```
<activity android:name=".MainActivity" android:theme="@style/DefaultCityPickerTheme">
  ......
</activity>
```

如果想用自己的Theme——A，重新定义一个继承于A的新theme——B，添加DefaultCityPickerTheme中的item，然后使用B即可：
<item name="cpCancelTextSize">@dimen/cp_cancel_text_size</item>
        <item name="cpCancelTextColor">@color/cp_color_gray</item>

        <item name="cpClearTextIcon">@mipmap/cp_icon_clear_all</item>
        <item name="cpSearchTextSize">@dimen/cp_search_text_size</item>
        <item name="cpSearchTextColor">@color/cp_color_gray_dark</item>
        <item name="cpSearchHintText">@string/cp_search_hint_text</item>
        <item name="cpSearchHintTextColor">@color/cp_color_gray_light</item>
        <item name="cpSearchCursorDrawable">@color/cp_color_gray_dark</item>

        <item name="cpListItemHeight">@dimen/cp_list_item_height</item>
        <item name="cpListItemTextSize">@dimen/cp_list_item_text_size</item>
        <item name="cpListItemTextColor">@color/cp_color_gray_deep</item>

        <item name="cpEmptyIcon">@mipmap/cp_icon_empty</item>
        <item name="cpEmptyIconWidth">@dimen/cp_empty_icon_width</item>
        <item name="cpEmptyIconHeight">@dimen/cp_empty_icon_height</item>
        <item name="cpEmptyText">@string/cp_no_result</item>
        <item name="cpEmptyTextSize">@dimen/cp_empty_text_size</item>
        <item name="cpEmptyTextColor">@color/cp_color_gray_deep</item>

        <item name="cpGridItemBackground">@drawable/cp_grid_item_bg</item>
        <item name="cpGridItemSpace">@dimen/cp_grid_item_space</item>

        <item name="cpSectionHeight">@dimen/cp_section_height</item>
        <item name="cpSectionTextSize">@dimen/cp_section_text_size</item>
        <item name="cpSectionTextColor">@color/cp_color_gray</item>
        <item name="cpSectionBackground">@color/cp_color_section_bg</item>

        <item name="cpIndexBarTextSize">@dimen/cp_index_bar_text_size</item>
        <item name="cpIndexBarNormalTextColor">@color/cp_color_gray</item>
        <item name="cpIndexBarSelectedTextColor">@color/cp_color_gray_dark</item>

        <item name="cpOverlayWidth">@dimen/cp_overlay_width</item>
        <item name="cpOverlayHeight">@dimen/cp_overlay_height</item>
        <item name="cpOverlayTextSize">@dimen/cp_overlay_text_size</item>
        <item name="cpOverlayTextColor">@android:color/white</item>
        <item name="cpOverlayBackground">@drawable/cp_overlay_bg</item>

**Comment by yangzai100** [comment]
之前是用一个activity写的加了主题的，后面放到其他的frgment里面就忘了，我的问题。。。谢谢大佬～

**Comment by luffykou** [comment]
好的，不客气。

你可以close这个issue。
