### ISSUE TITLE
若能够适配多种数据源，数据结构，专用范围会更大

### ISSUE THREAD

**Issue by chenyang1900** [zaaach/CityPicker#42]
见标题

**Comment by luffykou** [comment]
兄弟思维僵硬了啊。

字母快速检索不是通讯录的特权呀，城市选择为何不可？！

城市选择也不是非得“省市区/县三级联动选择”形式不可吧。

萝卜白菜各有所爱，人家开源的工具挺好的。兄弟不喜欢可以自己去码呀，何必来这里怼天怼地。

**Comment by chenyang1900** [comment]
一口老血喷出 ，真没怼啊 ，兄弟火气太大 。当时思考如何改成其他的类似东西。表达这么好的东西，只能用在城市选择上太可惜了 。能够适配多种数据源，数据结构，专用范围会更大，会更好。所以才来评论两句。希望这个库更好 ;看来前面的用词不够谨慎 ，带有了贬义。苦逼 ，@luffykou
