### ISSUE TITLE
高度测量问题， # 符号被遮挡

### ISSUE THREAD

**Issue by Yanqilong** [zaaach/CityPicker#43]
代码版本：2.0
高度测量问题， # 符号被遮挡 ，看下效果图:

<img src="http://or45zpyfw.bkt.clouddn.com/18-4-16/84443418.jpg" width="100">

我这页面顶部有个 EdiText，如果触发EdiText弹出软盘，然后收会软盘，#就可以显示出来，也就正常了
大佬这是什么问题？

**Comment by zaaach** [comment]
是单独使用了IndexSideBar这个控件吗？这个本身没有重写onMeasure方法

**Comment by Yanqilong** [comment]
结合了 RecyclerView 一起使用

**Comment by zaaach** [comment]
最新版v2.0.3里修复了字符被遮挡的问题，你看下吧
