### ISSUE TITLE
搜索时定位城市和热门城市显示错误

### ISSUE THREAD

**Issue by YueSeSuiFeng** [zaaach/CityPicker#45]
搜索时定位城市和热门城市显示错误
[
![screenshot_2018-05-18-11-04-02-336_com app newdem](https://user-images.githubusercontent.com/26158197/40214157-cf21d41a-5a8b-11e8-9933-443e8b27421a.png)
](url)

**Comment by zaaach** [comment]
试下最新版v2.0.3
