### ISSUE TITLE
城市数据更改问题

### ISSUE THREAD

**Issue by mark2L** [zaaach/CityPicker#51]
@zaaach 你好，我发现你在项目里面用的城市编码是全国城市天气的代码，而我现在的需求是使用行政编码，所以想请教如何修改项目中的数据源，是需要把项目导出来，自己修改里面的db文件吗？

**Comment by tianyanzi** [comment]
我怎么才能使用自己的city数据呢

**Comment by superzhangbao** [comment]
@mark2L 兄弟  你找到修改数据源的方法了吗，我也需要用自己的数据源

**Comment by salmanit** [comment]
搜索结果里返回了作者的city，完事你拿着city的name去你自己的数据库里查找好了，城市的话应该都一样吧，如果你的数据和作者都不一样那就没辙了，如果只是多了一些其他数据我感觉可以这样操作，就不需要复制代码了
