### ISSUE TITLE
希望能增加dialogFragment消失的监听事件

### ISSUE THREAD

**Issue by CaoyangLee** [zaaach/CityPicker#61]

**Comment by zaaach** [comment]
OnPickListener就是消失之后的回调

**Comment by CaoyangLee** [comment]
好  谢谢

Bro0cL <notifications@github.com> 于 2018年10月11日周四 12:57写道：

**Comment by CaoyangLee** [comment]
但是我如果按返回键呢？是否也会触发？

李朝阳 <caoyanglee92@gmail.com> 于 2018年10月11日周四 13:40写道：
