### ISSUE TITLE
依赖使用implementation无法引入

### ISSUE THREAD

**Issue by KCrason** [zaaach/CityPicker#67]
2.0.3使用使用implementation无法引入，提示“Failed to resolve: com.github.zaaach:CityPicker:2.0.3”。

**Comment by zaaach** [comment]
添加maven 了没？如果不行就试试jcenter方式吧，implementation 'com.zaaach:citypicker:2.0.3'

**Comment by KCrason** [comment]
@zaaach 加了，jcenter这个没问题，估计是你那边上传有问题。

**Comment by zaaach** [comment]
之前网络不好，jcenter传不上去，就传了jitpack，可能没传上去。。。

**Comment by songshitong** [comment]
添加了maven { url "https://jitpack.io" }，使用implementation 'com.zaaach:citypicker:2.0.3' 也是失败的；
但是使用implementation 'com.zaaach:citypicker:2.0.3'是成功的，麻烦楼主做下修复

**Comment by 917960559** [comment]
implementation 'com.zaaach:CityPicker:2.0.3'	//必选
readme这里的大写首字母要换成小写字母才可以依赖成功
正确的依赖方法：
implementation 'com.zaaach:citypicker:2.0.3'

**Comment by dzg709580412** [comment]
> implementation 'com.zaaach:citypicker:2.0.3'



> implementation 'com.zaaach:CityPicker:2.0.3'	//必选
> readme这里的大写首字母要换成小写字母才可以依赖成功
> 正确的依赖方法：
> implementation 'com.zaaach:citypicker:2.0.3'

你可真是个小机灵鬼呢

**Comment by zaaach** [comment]
已更正

**Comment by dzg709580412** [comment]
> 已更正
请问下您这个有 历史城市 这个功能吗？

**Comment by zaaach** [comment]
@dzg709580412 目前是没有的
