### ISSUE TITLE
请教一下，无法打开china_cities.db

### ISSUE THREAD

**Issue by syBlack** [zaaach/CityPicker#7]
您好，请问下我按照这个代码在eclipse上写了一遍之后无法打开china_cities.db，我看了下目录里面没有database这个目录，但是mkdirs这个方法执行了。Log：Failed to open database '/data/data/database/china_cities.db'；android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database。

**Comment by zaaach** [comment]
DB_PATH = File.separator + "data"
                + Environment.getDataDirectory().getAbsolutePath() + File.separator
                + context.getPackageName() + File.separator + "databases" + File.separator;
你看下DBManager.java这个文件里上面这个是不是少写了包名

**Comment by syBlack** [comment]
是少了 context.getPackageName()，已经弄出来了，谢谢了
