### ISSUE TITLE
定位失败

### ISSUE THREAD

**Issue by ionetwogo** [zaaach/CityPicker#8]
你好！我按照你提供的方法设置，并且申请了高德的key，但还是显示定位失败，高德的key校验了sha1也没有问题。检查出来是定位权限问题，不知道你这个是否对6.0及以上版本还需做何处理？

**Comment by zaaach** [comment]
打包签名apk才能定位成功

**Comment by ionetwogo** [comment]
是6.0及以上的权限问题，我同样签名包放在4.4的没问题，放在6.0的就获取不到权限，按照高德那边的错误码是说明是权限没给。我想可能你这个需要做点改动，针对6.0及以上版本做运行时权限的获取。在这谢谢你了，这是个使用很方便的库。可能我这边仍然对于需要运行时获取权限的问题做下解决。（^_^）

**Comment by JiangShuLiang** [comment]
这位朋友你解决了吗？我这儿也一样，6.0系统就定位失败，其他4.0和5.0都能定位成功

**Comment by JiangShuLiang** [comment]
希望作者能针对6.0系统权限问题做下改善，一直用你这个库，很好用也很喜欢。先感谢了！

**Comment by Evenss** [comment]
我6.0系统，手动开启的定位的权限，还是定位失败，这是怎么回事？T^T

**Comment by zaaach** [comment]
最新版已和定位SDK解耦
