### ISSUE TITLE
CityListAdapter有个bug,望大神修复下

### ISSUE THREAD

**Issue by Kwanloyal** [zaaach/CityPicker#9]
/**
     * 更新定位状态
     * @param state
     */
    public void updateLocateState(int state, String city){
        this.locateState = state;
        this.locatedCity = city;
        //notifyDataSetChanged();  导致地址选择拖拉无效,而且定位完成不会主动更新定位城市
    }

**Comment by zaaach** [comment]
你具体的使用场景是什么？

**Comment by Kwanloyal** [comment]
就把你这个CityPickerActivity放到我项目中打开，第一次是可以拖动的，然而选择了一次城市之后，再进你这个Activity,右边那个拖拉控件就无法拖动了。

**Comment by zaaach** [comment]
恩明白了，我再检查下哈

**Comment by zaaach** [comment]
@Kwanloyal 使用最新的2.0版本吧
