### ISSUE TITLE
玩完

### ISSUE THREAD

**Issue by AdminQQZ** [zaaach/CityPicker#92]
![微信图片_20191127094459](https://user-images.githubusercontent.com/12959954/69686399-a091ce80-10fa-11ea-9f83-a40f8812e133.png)

**Comment by AdminQQZ** [comment]
import com.huiyunyu.opsrc.citypicker.model.CityPickerConfig;
![image](https://user-images.githubusercontent.com/12959954/69689247-611bb000-1103-11ea-9432-8e7344364df8.png)

**Comment by zaaach** [comment]
主题设置了没？

**Comment by AdminQQZ** [comment]
设置主题后就好了。嘻嘻。
太粗心了
